env         = "dev"
db          = "sql"
key         = "secret/tfstate/dev/pite-dldeb-dev-sql-admin.tfstate"
bucket      = "dafehv-terraform-state-dev-904626469165"
region      = "eu-central-1"
assume_role = ""
