env             = "stage"
db              = "sql"
key             = "secret/tfstate/stage/stage-sql-secret-admin.tfstate"
bucket          = "terraform-state-stage-609258630391"
region          = "eu-west-1"
db_pass          = "ccmdbAdmin"
assume_role     = "" 
