env         = "dev"
db          = "sql"
key         = "secret/tfstate/dev/pite-dldeb-dev-sql-admin.tfstate"
bucket      = "terraform-state-dev-609258630391"
region      = "eu-central-1"
assume_role = ""
