env         = "stage"
db          = "sql"
key         = "infra/tfstate/stage/secret/pite-dldeb-stage-sql-admin.tfstate"
bucket      = "dafehv-terraform-state-stage-904626469165"
region      = "eu-central-1"
assume_role = ""